---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

- name: set prometheus_use_service = True, if not defined
  set_fact:
    prometheus_use_service: True
  when: prometheus_use_service is not defined



- block:

  - name: use systemd for CentOS >= 7
    set_fact:
      prometheus_node_exporter_use_systemd: true
    when: ansible_distribution == "CentOS" and ansible_distribution_version|int >= 7

  - name: use systemd for RHEL >= 7
    set_fact:
      prometheus_node_exporter_use_systemd: true
    when: ansible_distribution == "Red Hat Enterprise Linux" and ansible_distribution_version|int >= 7

  - name: use systemd for Debian >= 8
    set_fact:
      prometheus_node_exporter_use_systemd: true
    when: ansible_distribution == "Debian" and ansible_distribution_version|int >= 8

  - name: use systemd for Ubuntu >= 16.04
    set_fact:
      prometheus_node_exporter_use_systemd: true
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version|int >= 16

  when: prometheus_node_exporter_use_systemd is not defined

- name: configure prometheus_systemd_unit_dir for SLES
  set_fact:
    prometheus_systemd_unit_dir: "/usr/lib/systemd/system"
  when: ansible_os_family == "Suse" and prometheus_node_exporter_use_systemd == True

- name: configure prometheus_systemd_unit_dir for user level systemd
  set_fact:
    prometheus_systemd_unit_dir: "{{ yb_home_dir }}/.config/systemd/user"
  when: use_user_level_systemd is defined and use_user_level_systemd|bool

- name: use traditional SysV init, otherwise
  set_fact:
    prometheus_node_exporter_use_systemd: false
  when: prometheus_node_exporter_use_systemd is not defined


- name: set internal variable platform-suffix for convenience
  set_fact:
    prometheus_platform_suffix: "linux-amd64"
  when: ansible_userspace_bits == "64"

- name: set internal variable platform-suffix for convenience
  set_fact:
    prometheus_platform_suffix: "linux-386"
  when: ansible_userspace_bits == "32"
