---
# file: handlers/main.yml
#

- name: restart prometheus
  service: name=prometheus state=restarted
  when: prometheus_use_service|bool

- name: reload prometheus
  service: name=prometheus state=reloaded
  when: prometheus_use_service|bool

- name: stop prometheus
  service: name=prometheus state=stopped
  when: prometheus_use_service|bool



- name: restart node_exporter
  systemd:
    name: node-exporter
    state: restarted
    user: yes

- name: reload node_exporter
  systemd:
    name: node-exporter
    state: reloaded
    user: yes

- name: stop node_exporter
  systemd:
    name: node-exporter
    state: stopped
    user: yes



- name: restart alertmanager
  service: name=alertmanager state=restarted
  when: prometheus_use_service|bool

- name: reload alertmanager
  service: name=alertmanager state=reloaded
  when: prometheus_use_service|bool

- name: stop alertmanager
  service: name=alertmanager state=stopped
  when: prometheus_use_service|bool
